# Generated by Django 2.2 on 2019-05-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='header',
            new_name='height',
        ),
        migrations.AddField(
            model_name='block',
            name='merkleRoot',
            field=models.CharField(default=0, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='previousHash',
            field=models.CharField(default=0, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='tCounter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='timestamp',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='version',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='hashValue',
            field=models.CharField(max_length=350),
        ),
    ]
